### ISSUE TITLE
Not escaped </script> tag in feed

### ISSUE THREAD

**Issue by rezad1393** [wallabag/android-app#373] opened 2016-12-17 15:50 UTC
recently I tried the service provided at v2.wallabag.org and it works in browser and I used that in wallabag app too and it worked for a while but now it had stopped working. with "unknown error".

**Comment by di72nn** [comment] 2016-12-17 18:30
Try to press "Autofill" in connection settings, it may give you more specific error.

Can you get logs (of the time when the error happens) with these steps:
 * Get the process ID:
  `adb shell pidof fr.gaulupeau.apps.InThePoche`
 * Filter logcat:
  `adb shell 'logcat | grep <the process id from the previous step>'`

**Comment by rezad1393** [comment] 2016-12-19 08:01
first one didnt help.

`
12-19 11:30:37.512 I/ActivityManager(2993): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity bnds=[107,1671][235,1799] (has extras)} from uid 10025 on display 0
12-19 11:30:37.566 I/ActivityManager(2993): Start proc 26736:fr.gaulupeau.apps.InThePoche/u0a239 for activity fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity
12-19 11:30:37.673 W/System  (26736): ClassLoader referenced unknown path: /data/app/fr.gaulupeau.apps.InThePoche-1/lib/arm
12-19 11:30:39.665 E/BGService(26736): 	at fr.gaulupeau.apps.Poche.network.FeedUpdater.parseNextText(FeedUpdater.java:420)
12-19 11:30:39.665 E/BGService(26736): 	at fr.gaulupeau.apps.Poche.network.FeedUpdater.parseItem(FeedUpdater.java:406)
12-19 11:30:39.665 E/BGService(26736): 	at fr.gaulupeau.apps.Poche.network.FeedUpdater.processFeed(FeedUpdater.java:264)
12-19 11:30:39.665 E/BGService(26736): 	at fr.gaulupeau.apps.Poche.network.FeedUpdater.updateByFeed(FeedUpdater.java:168)
12-19 11:30:39.665 E/BGService(26736): 	at fr.gaulupeau.apps.Poche.network.FeedUpdater.updateAllFeeds(FeedUpdater.java:122)
12-19 11:30:39.665 E/BGService(26736): 	at fr.gaulupeau.apps.Poche.network.FeedUpdater.update(FeedUpdater.java:96)
12-19 11:30:39.665 E/BGService(26736): 	at fr.gaulupeau.apps.Poche.service.BGService.updateFeed(BGService.java:363)
12-19 11:30:39.665 E/BGService(26736): 	at fr.gaulupeau.apps.Poche.service.BGService.onHandleIntent(BGService.java:99)
12-19 11:30:39.901 I/ActivityManager(2993): Displayed fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity: +2s362ms`

**Comment by di72nn** [comment] 2016-12-19 08:39
1. Start the command to get logs.
2. Do something so the "Unknown error" notification appear.
3. Copy the log messages for all this time.

**Comment by rezad1393** [comment] 2016-12-19 11:52
that is exactly what I did.
but I did it with an app on the tablet to get the logs.

**Comment by di72nn** [comment] 2016-12-19 12:29
Yeah, sorry, the logs indeed contain some useful information. But the error seems to be truncated.
This part usually starts with exception name and error message, and may continue with "caused by" (it is likely to have "E/BGService" right after timestamp too):
```
12-19 11:30:39.665 E/BGService(26736): 	at fr.gaulupeau.apps.Poche.network.FeedUpdater.parseNextText(FeedUpdater.java:420)
12-19 11:30:39.665 E/BGService(26736): 	at fr.gaulupeau.apps.Poche.network.FeedUpdater.parseItem(FeedUpdater.java:406)
12-19 11:30:39.665 E/BGService(26736): 	at fr.gaulupeau.apps.Poche.network.FeedUpdater.processFeed(FeedUpdater.java:264)
12-19 11:30:39.665 E/BGService(26736): 	at fr.gaulupeau.apps.Poche.network.FeedUpdater.updateByFeed(FeedUpdater.java:168)
12-19 11:30:39.665 E/BGService(26736): 	at fr.gaulupeau.apps.Poche.network.FeedUpdater.updateAllFeeds(FeedUpdater.java:122)
12-19 11:30:39.665 E/BGService(26736): 	at fr.gaulupeau.apps.Poche.network.FeedUpdater.update(FeedUpdater.java:96)
12-19 11:30:39.665 E/BGService(26736): 	at fr.gaulupeau.apps.Poche.service.BGService.updateFeed(BGService.java:363)
12-19 11:30:39.665 E/BGService(26736): 	at fr.gaulupeau.apps.Poche.service.BGService.onHandleIntent(BGService.java:99)
```

The best guess is that the server provides incorrectly formatted RSS feed (maybe some specific symbols in an article are not escaped properly). But it may be caused by something completely different since we don't see the error message here.

Can you repeat the procedure and try to get more complete logs? Maybe in the app you use to get logs some extra filters are enabled that prevented the exception message to be displayed? Or maybe it was just a one-time glitch and the next time the log will be full.
There should be something else around the fragment I quoted.

**Comment by rezad1393** [comment] 2016-12-19 12:44
If I use the poche as filter then that is all all I get.
If I dont then I get the all the android massages (which are a massive and cant separate them)
maybe this has to do with a wallabag.org website providing a paid wallabag.li that it advertises on it website.
maybe they remove the web sync of the v2.wallabag.org so that people would buy that.

**Comment by di72nn** [comment] 2016-12-19 13:11
Yes, that's good, thanks.
This is definitely a server-side issue. The `</script>` tag is not escaped:
```
12-19 16:15:06.290 E/BGService(2946): org.xmlpull.v1.XmlPullParserException: expected: /description read: script (position:END_TAG </script>@1408:713 in java.io.InputStreamReader@3576efd) 
```

The error is caused by a specific article. If you want, I can help you to track down the problem article, but it'll take some more effort.

> maybe they remove the web sync of the v2.wallabag.org so that people would buy that

That's not the issue here. Though they may disable v2.wallabag.org soon, but I don't track it, so can't be sure.

**Comment by di72nn** [comment] 2016-12-19 15:26
When #377 gets merged and released the app will try to provide more information regarding such errors.

For the record: the issue was already mentioned https://github.com/wallabag/android-app/pull/282#issuecomment-230102820 https://github.com/wallabag/android-app/pull/282#issuecomment-245249367, but there were no investigation on it's origin.

**Closed** 2017-01-07 16:36 UTC
