### ISSUE TITLE
[feature request] Option to allow selecting tags on add

### ISSUE THREAD

**Issue by mredaelli** [wallabag/android-app#1009] opened 2020-06-27 19:05 UTC
### Actual behaviour
When adding a link by using "Share" from another app, it is saved directly with no further interaction

### Expected behaviour
Have a setting in the app so that the user can be presented with a dialogue to let them enter/choose tags for the item.

**Comment by di72nn** [comment] 2020-06-27 19:36
Duplicate of #675.
It's been implemented recently - available in our latest beta ([APK](https://github.com/wallabag/android-app/releases/tag/2.4.0-beta.3), [beta on Google Play](https://play.google.com/apps/testing/fr.gaulupeau.apps.InThePoche), [eventually on F-Droid](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7000)).

**Closed by di72nn** 2020-06-27 19:36 UTC
