### ISSUE TITLE
tag creation 

### ISSUE THREAD

**Issue by foxmask** [wallabag/android-app#231] opened 2016-04-28 06:07 UTC
It could be helpful to be able to create tag from the app / or even when we add a post

**Comment by Strubbl** [comment] 2016-05-03 14:53
There are a lot of open requirements to implement this feature:

It needs wallabag v2.1 https://github.com/wallabag/wallabag/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.1.0
especially https://github.com/wallabag/wallabag/issues/1984

And of course it needs our app to use the API. Currently we use the RSS feeds and not the API.

**Comment by huegelc** [comment] 2016-06-13 17:24
This feature would be great

**Comment by anarcat** [comment] 2016-11-30 03:22
this seems like a dupe of #195 or #116. the API is ready though...

**Comment by di72nn** [comment] 2016-11-30 09:45
Closed in favor of #116.

**Closed by di72nn** 2016-11-30 09:45 UTC
Labels: Feature
