### ISSUE TITLE
Dark with high contrast theme: Active menu item is not readable

### ISSUE THREAD

**Issue by pVesian** [wallabag/android-app#558] opened 2017-06-12 10:44 UTC
Hi,

Please look at the "tags" link below. 
Thanks ! 

![tmp_10556-screenshot_20170612-1237272097911482](https://user-images.githubusercontent.com/3509962/27030414-69b2c1be-4f6c-11e7-9c5f-5c15e56f63b1.png)

**Comment by ngosang** [comment] 2017-06-20 01:53
Duplicate of #552

**Comment by di72nn** [comment] 2017-06-20 10:13
Thanks for reporting. Added this screenshot to #552.

**Closed by di72nn** 2017-06-20 10:13 UTC
Labels: Bug, UI
