### ISSUE TITLE
Reduce header height on article

### ISSUE THREAD

**Issue by pVesian** [wallabag/android-app#569] opened 2017-06-16 23:09 UTC
Hi,
Since I'm used to Pocket, I'm going to suggest a feature they have: when reading an article, a tap will hide everything, the menu & even the Android notification bar. I think they do a fullscreen. That way there is much more content on screen. It reappears on a tap or when scrolling up.
Related to #442, but this is for article only.
Thanks!

**Comment by Strubbl** [comment] 2017-06-17 07:27
I guess, this is a duplicate of #114

**Comment by pVesian** [comment] 2017-06-17 12:34
#114 doesn't seem specific to an article. @tcitworld, thoughts?

**Comment by tcitworld** [comment] 2017-06-17 14:17
#114 should mostly be on article view for comfort, on the rest it's not that important.

**Comment by pVesian** [comment] 2017-06-17 17:25
@Strubbl So it appears indeed to be a duplicate. Can you please close it?

**Closed** 2017-06-17 18:00 UTC
