### ISSUE TITLE
adding a PDF link breaks synchronisation

### ISSUE THREAD

**Issue by silberzwiebel** [wallabag/android-app#692] opened 2018-01-29 09:51 UTC
How to reproduce:
Add a URL that points to a PDF link to the android app.
Synchronize with the server.

I get (with my self-hosted server version 2.3.1):

```
com.di72nn.stuff.wallabag.apiwrapper.excpetions.UnsuccessfulResponseException: HTTP response: 500 Internal Server Error
```

and nothing is synchronized. Despite from re-installing the app (which I haven't done yet), I see no other way of removing the not working article.
Potentially, this is also an issue on the server side?

**Comment by Strubbl** [comment] 2018-01-29 17:14
This issue seems to be a duplicate of #483 . 483 is not directly about PDF, but it's the same server-side error and sync is also blocked. 

Yes, this is also an issue with the server side, maybe this one https://github.com/wallabag/wallabag/issues/3576 ?

**Comment by silberzwiebel** [comment] 2018-01-30 13:10
Okay, then maybe we should close this issue as a duplicate? 
For me the solution for the android app would be what @di72nn [suggested here](https://github.com/wallabag/android-app/issues/483#issuecomment-286229664) -- although I would argue to implement this is in any case and not making the server responsible for correct behavior. Things go wrong and I think it's better to be prepared for this. Otherwise, the android app becomes un-syncable after one wrong article.

Regarding the server issue: My server is still running fine (didn't check the logs yet), different than in https://github.com/wallabag/wallabag/issues/3576
By the way, [here is the PDF](http://www.richardpoynder.co.uk/Copyright.pdf)  I added via the app.

**Closed** 2018-01-30 21:04 UTC
