### ISSUE TITLE
Crash when marking article as read

### ISSUE THREAD

**Issue by tcitworld** [wallabag/android-app#125] opened 2015-11-15 16:23 UTC
http://pastebin.com/jeskKvT5

E/AndroidRuntime(11085): Process: fr.gaulupeau.apps.InThePoche, PID: 11085
E/AndroidRuntime(11085): 	at fr.gaulupeau.apps.Poche.network.tasks.ToggleArchiveTask.onPostExecute(ToggleArchiveTask.java:58)
E/AndroidRuntime(11085): 	at fr.gaulupeau.apps.Poche.network.tasks.ToggleArchiveTask.onPostExecute(ToggleArchiveTask.java:13)
E/AndroidRuntime(18699): Process: fr.gaulupeau.apps.InThePoche, PID: 18699
E/AndroidRuntime(18699): 	at fr.gaulupeau.apps.Poche.network.tasks.ToggleArchiveTask.onPostExecute(ToggleArchiveTask.java:58)
E/AndroidRuntime(18699): 	at fr.gaulupeau.apps.Poche.network.tasks.ToggleArchiveTask.onPostExecute(ToggleArchiveTask.java:13)
E/AndroidRuntime(19440): Process: fr.gaulupeau.apps.InThePoche, PID: 19440
E/AndroidRuntime(19440): 	at fr.gaulupeau.apps.Poche.network.tasks.ToggleArchiveTask.onPostExecute(ToggleArchiveTask.java:58)
E/AndroidRuntime(19440): 	at fr.gaulupeau.apps.Poche.network.tasks.ToggleArchiveTask.onPostExecute(ToggleArchiveTask.java:13)
E/AndroidRuntime(19949): Process: fr.gaulupeau.apps.InThePoche, PID: 19949
E/AndroidRuntime(19949): 	at fr.gaulupeau.apps.Poche.network.tasks.ToggleArchiveTask.onPostExecute(ToggleArchiveTask.java:58)
E/AndroidRuntime(19949): 	at fr.gaulupeau.apps.Poche.network.tasks.ToggleArchiveTask.onPostExecute(ToggleArchiveTask.java:13)
E/AndroidRuntime(20327): Process: fr.gaulupeau.apps.InThePoche, PID: 20327
E/AndroidRuntime(20327): 	at fr.gaulupeau.apps.Poche.network.tasks.ToggleArchiveTask.onPostExecute(ToggleArchiveTask.java:58)
E/AndroidRuntime(20327): 	at fr.gaulupeau.apps.Poche.network.tasks.ToggleArchiveTask.onPostExecute(ToggleArchiveTask.java:13)
E/AndroidRuntime(20644): Process: fr.gaulupeau.apps.InThePoche, PID: 20644
E/AndroidRuntime(20644): 	at fr.gaulupeau.apps.Poche.network.tasks.ToggleArchiveTask.onPostExecute(ToggleArchiveTask.java:58)
E/AndroidRuntime(20644): 	at fr.gaulupeau.apps.Poche.network.tasks.ToggleArchiveTask.onPostExecute(ToggleArchiveTask.java:13)
I/ActivityManager(  666): START u0 {act=android.intent.action.SEND typ=text/plain flg=0xb080001 cmp=fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.BagItProxyActivity (has clip) (has extras)} from uid 10136 on display 0
V/WindowManager(  666): addAppToken: AppWindowToken{1098fec2 token=Token{30e23f0d ActivityRecord{1c0075a4 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.BagItProxyActivity t122}}} to stack=1 task=122 at 0
I/ActivityManager(  666): Start proc 16182:fr.gaulupeau.apps.InThePoche/u0a185 for activity fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.BagItProxyActivity
V/WindowManager(  666): Adding window Window{17c7db2f u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.BagItProxyActivity} at 11 of 18 (after Window{3d78055b u0 android/com.android.internal.app.ChooserActivity})
V/WindowManager(  666): Adding window Window{206d42c5 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.BagItProxyActivity} at 11 of 19 (before Window{17c7db2f u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.BagItProxyActivity})
V/WindowManager(  666): not Base app: Adding window Window{28644641 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.BagItProxyActivity} at 12 of 19
I/ActivityManager(  666): START u0 {act=android.intent.action.SEND typ=text/plain flg=0xb080001 cmp=fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.BagItProxyActivity (has clip) (has extras)} from uid 10136 on display 0
V/WindowManager(  666): addAppToken: AppWindowToken{2f87d0f5 token=Token{30eafe2c ActivityRecord{164c51df u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.BagItProxyActivity t123}}} to stack=1 task=123 at 0
V/WindowManager(  666): Adding window Window{2b4e2cfb u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.BagItProxyActivity} at 11 of 18 (after Window{20b13083 u0 android/com.android.internal.app.ChooserActivity})
V/WindowManager(  666): Adding window Window{ad18771 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.BagItProxyActivity} at 11 of 19 (before Window{2b4e2cfb u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.BagItProxyActivity})
V/WindowManager(  666): not Base app: Adding window Window{3b2629ad u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.BagItProxyActivity} at 12 of 19
I/ActivityManager(  666): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ListArticlesActivity bnds=[274,223][417,387] (has extras)} from uid 10090 on display 0
V/WindowManager(  666): addAppToken: AppWindowToken{6f6ccbb token=Token{16e9154a ActivityRecord{2b71fab5 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ListArticlesActivity t124}}} to stack=1 task=124 at 0
V/WindowManager(  666): Adding window Window{19703a2 u0 Starting fr.gaulupeau.apps.InThePoche} at 9 of 16 (after Window{23148190 u0 org.mariotaku.twidere/org.mariotaku.twidere.activity.support.LinkHandlerActivity})
V/WindowManager(  666): Adding window Window{575b31c u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ListArticlesActivity} at 9 of 17 (before Window{19703a2 u0 Starting fr.gaulupeau.apps.InThePoche})
V/WindowManager(  666): Adding window Window{1188d6c6 u0 PopupWindow:106cd17f} at 10 of 17 (after Window{575b31c u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ListArticlesActivity})
V/WindowManager(  666): Adding window Window{199a1b4c u0 PopupWindow:2378f25a} at 10 of 18 (after Window{575b31c u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ListArticlesActivity})
V/WindowManager(  666): not Base app: Adding window Window{1aa8fb02 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ListArticlesActivity} at 11 of 18
I/ActivityManager(  666): Killing 16182:fr.gaulupeau.apps.InThePoche/u0a185 (adj 13): remove task
I/WindowState(  666): WIN DEATH: Window{575b31c u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ListArticlesActivity}
D/Finsky  (19961): [1] DownloadQueueImpl.notifyProgress: fr.gaulupeau.apps.InThePoche: onProgress 1905871/1905871 Status: 200.
D/Finsky  (19961): [1] DownloadImpl.setState: fr.gaulupeau.apps.InThePoche from 2 to 3.
D/Finsky  (19961): [1] DownloadQueueImpl.onComplete: fr.gaulupeau.apps.InThePoche: onComplete
D/Finsky  (19961): [1] DownloadQueueImpl.remove: Download fr.gaulupeau.apps.InThePoche removed from DownloadQueue
D/Finsky  (19961): [1] InstallerTask.advanceState: Prepare to copy fr.gaulupeau.apps.InThePoche (fr.gaulupeau.apps.InThePoche) from content://downloads/my_downloads/527 (expect 1905871 bytes)
D/Finsky  (19961): [1] 7.onPostExecute: Successfully copied APK to update fr.gaulupeau.apps.InThePoche (fr.gaulupeau.apps.InThePoche)
D/Finsky  (19961): [1] InstallerTask.advanceState: Begin install of fr.gaulupeau.apps.InThePoche
D/PackageManager(  666): Renaming /data/app/vmdl1787688200.tmp to /data/app/fr.gaulupeau.apps.InThePoche-2
I/ActivityManager(  666): Force stopping fr.gaulupeau.apps.InThePoche appid=10185 user=-1: uninstall pkg
I/PackageManager(  666): Package fr.gaulupeau.apps.InThePoche codePath changed from /data/app/fr.gaulupeau.apps.InThePoche-1 to /data/app/fr.gaulupeau.apps.InThePoche-2; Retaining data and using new
I/PackageManager(  666): Running dexopt on: /data/app/fr.gaulupeau.apps.InThePoche-2/base.apk pkg=fr.gaulupeau.apps.InThePoche isa=arm vmSafeMode=false
I/dex2oat (20200): /system/bin/dex2oat --zip-fd=6 --zip-location=/data/app/fr.gaulupeau.apps.InThePoche-2/base.apk --oat-fd=7 --oat-location=/data/dalvik-cache/arm/data@app@fr.gaulupeau.apps.InThePoche-2@base.apk@classes.dex --instruction-set=arm --instruction-set-features=div --runtime-arg -Xms64m --runtime-arg -Xmx512m -j3 --no-watch-dog --swap-fd=10
I/ActivityManager(  666): Force stopping fr.gaulupeau.apps.InThePoche appid=10185 user=-1: update pkg
W/PackageManager(  666): Code path for pkg : fr.gaulupeau.apps.InThePoche changing from /data/app/fr.gaulupeau.apps.InThePoche-1 to /data/app/fr.gaulupeau.apps.InThePoche-2
W/PackageManager(  666): Resource path for pkg : fr.gaulupeau.apps.InThePoche changing from /data/app/fr.gaulupeau.apps.InThePoche-1 to /data/app/fr.gaulupeau.apps.InThePoche-2
I/ActivityManager(  666): Force stopping fr.gaulupeau.apps.InThePoche appid=10185 user=0: pkg removed
D/BackupManagerService(  666): Received broadcast Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:fr.gaulupeau.apps.InThePoche flg=0x4000010 (has extras) }
D/BackupManagerService(  666): Received broadcast Intent { act=android.intent.action.PACKAGE_ADDED dat=package:fr.gaulupeau.apps.InThePoche flg=0x4000010 (has extras) }
W/BackupManagerService(  666): Removing schedule queue dupe of fr.gaulupeau.apps.InThePoche
D/Finsky  (19961): [1] 3.installSucceeded: Successful install of fr.gaulupeau.apps.InThePoche
D/PackageBroadcastService(17968): Received broadcast action=android.intent.action.PACKAGE_REMOVED and uri=fr.gaulupeau.apps.InThePoche
D/PackageBroadcastService(17968): Received broadcast action=android.intent.action.PACKAGE_ADDED and uri=fr.gaulupeau.apps.InThePoche
D/h       (17968): Processing package: fr.gaulupeau.apps.InThePoche
D/a       (17968): Look up (fr.gaulupeau.apps.InThePoche:14) returned no result
D/h       (17968): Starting Hash for package fr.gaulupeau.apps.InThePoche:1.9
D/h       (17968): Package fr.gaulupeau.apps.InThePoche's hash: e6f140d9e1c2ef4af8e7428fb7f42510cba94a777e7aa91fa252c7930af27ff1
D/a       (17968): Look up (fr.gaulupeau.apps.InThePoche:14) returned no result
D/h       (17968): Saved the app info in cache for package:fr.gaulupeau.apps.InThePoche.
I/UpdateIcingCorporaServi(16474): Updating corpora: APPS=fr.gaulupeau.apps.InThePoche, CONTACTS=MAYBE
D/PackageBroadcastService(17968): Received broadcast action=android.intent.action.PACKAGE_REPLACED and uri=fr.gaulupeau.apps.InThePoche
D/h       (17968): Processing package: fr.gaulupeau.apps.InThePoche
D/GassUtils(17968): Found app info for package fr.gaulupeau.apps.InThePoche:14. Hash: e6f140d9e1c2ef4af8e7428fb7f42510cba94a777e7aa91fa252c7930af27ff1
D/h       (17968): Found info for package fr.gaulupeau.apps.InThePoche in db.
I/Timeline( 1228): Timeline: Activity_launch_request id:fr.gaulupeau.apps.InThePoche time:16496100
I/ActivityManager(  666): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity bnds=[274,223][417,387] (has extras)} from uid 10090 on display 0
V/WindowManager(  666): addAppToken: AppWindowToken{2af0e765 token=Token{2fe9a85c ActivityRecord{13af86cf u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity t130}}} to stack=1 task=130 at 0
V/WindowManager(  666): Adding window Window{3f50a6f4 u0 Starting fr.gaulupeau.apps.InThePoche} at 8 of 15 (after Window{18a78315 u0 com.android.vending/com.google.android.finsky.activities.MainActivity})
I/ActivityManager(  666): Start proc 20496:fr.gaulupeau.apps.InThePoche/u0a185 for activity fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity
V/WindowManager(  666): Adding window Window{368373d5 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity} at 8 of 16 (before Window{3f50a6f4 u0 Starting fr.gaulupeau.apps.InThePoche})
I/ActivityManager(  666): Displayed fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity: +1s561ms
I/Timeline(  666): Timeline: Activity_windows_visible id: ActivityRecord{13af86cf u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity t130} time:16497726
I/Timeline(20496): Timeline: Activity_launch_request id:fr.gaulupeau.apps.InThePoche time:16504101
I/ActivityManager(  666): START u0 {cmp=fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity (has extras)} from uid 10185 on display 0
V/WindowManager(  666): addAppToken: AppWindowToken{1fe5b524 token=Token{e6429b7 ActivityRecord{238618b6 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity t130}}} to stack=1 task=130 at 1
W/ActivityManager(  666): Activity pause timeout for ActivityRecord{238618b6 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity t130}
E/FeedUpdater.updateByF(20496): 	at fr.gaulupeau.apps.Poche.network.tasks.UpdateFeedTask.getInputStream(UpdateFeedTask.java:201)
E/FeedUpdater.updateByF(20496): 	at fr.gaulupeau.apps.Poche.network.tasks.UpdateFeedTask.updateByFeed(UpdateFeedTask.java:157)
E/FeedUpdater.updateByF(20496): 	at fr.gaulupeau.apps.Poche.network.tasks.UpdateFeedTask.update(UpdateFeedTask.java:141)
E/FeedUpdater.updateByF(20496): 	at fr.gaulupeau.apps.Poche.network.tasks.UpdateFeedTask.doInBackground(UpdateFeedTask.java:76)
E/FeedUpdater.updateByF(20496): 	at fr.gaulupeau.apps.Poche.network.tasks.UpdateFeedTask.doInBackground(UpdateFeedTask.java:30)
V/WindowManager(  666): Adding window Window{250067b4 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity} at 8 of 16 (after Window{368373d5 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity})
I/Timeline(  666): Timeline: Activity_windows_visible id: ActivityRecord{238618b6 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity t130} time:16520922
I/Timeline(  666): Timeline: Activity_windows_visible id: ActivityRecord{13af86cf u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity t130} time:16548784
I/Timeline(20496): Timeline: Activity_launch_request id:fr.gaulupeau.apps.InThePoche time:16550999
I/ActivityManager(  666): START u0 {cmp=fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity (has extras)} from uid 10185 on display 0
V/WindowManager(  666): addAppToken: AppWindowToken{205df062 token=Token{1003732d ActivityRecord{a136644 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity t130}}} to stack=1 task=130 at 1
V/WindowManager(  666): Adding window Window{3f02a2b0 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity} at 9 of 16 (after Window{368373d5 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity})
I/ActivityManager(  666): Displayed fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity: +212ms (total +47s115ms)
I/Timeline(  666): Timeline: Activity_windows_visible id: ActivityRecord{a136644 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity t130} time:16551431
D/WallabagService(20496): executeRequest() start; autoRelogin: true
I/Timeline(  666): Timeline: Activity_windows_visible id: ActivityRecord{13af86cf u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity t130} time:16552999
D/WallabagService(20496): executeRequest() got response
D/WallabagService(20496): executeRequest() response is login page
D/WallabagService(20496): executeRequest() trying to re-login
D/WallabagService(20496): executeRequest() re-login response is OK; re-executing request
W/WindowManager(  666): Attempted to add application window with unknown token Token{1003732d ActivityRecord{a136644 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity t130 f}}.  Aborting.
E/AndroidRuntime(20496): Process: fr.gaulupeau.apps.InThePoche, PID: 20496
E/AndroidRuntime(20496): 	at fr.gaulupeau.apps.Poche.network.tasks.ToggleArchiveTask.onPostExecute(ToggleArchiveTask.java:58)
E/AndroidRuntime(20496): 	at fr.gaulupeau.apps.Poche.network.tasks.ToggleArchiveTask.onPostExecute(ToggleArchiveTask.java:13)
W/ActivityManager(  666):   Force finishing activity 1 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity
W/ActivityManager(  666): Activity pause timeout for ActivityRecord{13af86cf u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity t130 f}
W/PackageManager(  910): Failure retrieving resources for fr.gaulupeau.apps.InThePoche: Resource ID #0x0
I/WindowState(  666): WIN DEATH: Window{368373d5 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity}
I/ActivityManager(  666): Process fr.gaulupeau.apps.InThePoche (pid 20496) has died
I/Timeline( 1228): Timeline: Activity_launch_request id:fr.gaulupeau.apps.InThePoche time:16743515
I/ActivityManager(  666): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity bnds=[274,223][417,387] (has extras)} from uid 10090 on display 0
V/WindowManager(  666): addAppToken: AppWindowToken{2f85d3ea token=Token{5e60fd5 ActivityRecord{37b16c8c u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity t132}}} to stack=1 task=132 at 0
V/WindowManager(  666): Adding window Window{1d71648d u0 Starting fr.gaulupeau.apps.InThePoche} at 7 of 14 (after Window{3c2d9bff u0 acr.browser.lightning/acr.browser.lightning.activity.MainActivity})
I/ActivityManager(  666): Start proc 21645:fr.gaulupeau.apps.InThePoche/u0a185 for activity fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity
V/WindowManager(  666): Adding window Window{3111168 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity} at 7 of 15 (before Window{1d71648d u0 Starting fr.gaulupeau.apps.InThePoche})
I/ActivityManager(  666): Displayed fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity: +4s624ms
I/Timeline(  666): Timeline: Activity_windows_visible id: ActivityRecord{37b16c8c u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity t132} time:16748172
I/Timeline(21645): Timeline: Activity_launch_request id:fr.gaulupeau.apps.InThePoche time:16779657
I/ActivityManager(  666): START u0 {cmp=fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity (has extras)} from uid 10185 on display 0
V/WindowManager(  666): addAppToken: AppWindowToken{1120ac4b token=Token{38b7791a ActivityRecord{38cf4bc5 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity t132}}} to stack=1 task=132 at 1
V/WindowManager(  666): Adding window Window{1badd2be u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity} at 8 of 15 (after Window{3111168 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity})
I/ActivityManager(  666): Displayed fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity: +1s446ms
I/Timeline(  666): Timeline: Activity_windows_visible id: ActivityRecord{38cf4bc5 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity t132} time:16781484
D/WallabagService(21645): executeRequest() start; autoRelogin: true
I/Timeline(  666): Timeline: Activity_windows_visible id: ActivityRecord{37b16c8c u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity t132} time:16783320
W/PackageManager(  910): Failure retrieving resources for fr.gaulupeau.apps.InThePoche: Resource ID #0x0
D/WallabagService(21645): executeRequest() got response
D/WallabagService(21645): executeRequest() response is login page
D/WallabagService(21645): executeRequest() trying to re-login
E/AndroidRuntime(21645): Process: fr.gaulupeau.apps.InThePoche, PID: 21645
E/AndroidRuntime(21645): 	at fr.gaulupeau.apps.Poche.network.tasks.ToggleArchiveTask.onPostExecute(ToggleArchiveTask.java:58)
E/AndroidRuntime(21645): 	at fr.gaulupeau.apps.Poche.network.tasks.ToggleArchiveTask.onPostExecute(ToggleArchiveTask.java:13)

**Comment by di72nn** [comment] 2015-11-15 17:42
Looks like async tasks outlive an activity that spawned them, app crashes when the tasks try to show error message using old context (the activity). I'll fix it soon.

**Comment by tcitworld** [comment] 2015-11-15 17:43
Thanks for the explanation, I had quite some trouble to figure it out.

**Comment by di72nn** [comment] 2015-11-16 00:56
The easiest way to reproduce:
* set wrong username in settings,
* open article,
* press "Mark as read".

Expected result:
Error dialog is shown.

Actual result (before fix):
The app is force-closed by system.

**Comment by di72nn** [comment] 2015-11-17 09:20
Fixed. Unless proven otherwise.

**Closed by di72nn** 2015-11-17 09:20 UTC
Labels: bug, Needs to be reproduced
