### ISSUE TITLE
Malformed JSON

### ISSUE THREAD

**Issue by notabene** [wallabag/android-app#668] opened 2017-12-08 10:45 UTC
Hi,

Since yesterday I get this error message from Android:

> com.squareup.moshi.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $

This happens whenever I try to do something:

* favorite
* archive
* udapte all

HTH.

**Comment by notabene** [comment] 2017-12-08 11:01
By popular demand (@Simounet ;)) here are additional information:

* I use [NoRoot Firewall](https://play.google.com/store/apps/details?id=app.greyshirts.firewall&hl=en) to secure what goes out (hello, noisy Google) but Wallabag has all lights set to green: it can circulate information with no restriction.
* The Wallabag instance I use is [wallabag.it](https://app.wallabag.it/).

Cheers.

**Comment by ntnsndr** [comment] 2017-12-08 18:34
Same thing:

> com.squareup.moshi.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $

My Android app hasn't been able to load articles for several days. It has worked fine in the past.

**Comment by nicosomb** [comment] 2017-12-08 19:25
I think that we have a problem on wallabag.it. Do you know when did the first issue appear?

**Comment by ntnsndr** [comment] 2017-12-08 20:07
I can't be sure, but between 2 and 5 days ago.

**Comment by ntnsndr** [comment] 2017-12-08 20:09
Another thing: On my web interface, I noticed that one article I saved (I can't remember if it was via plugin or app) got replicated over and over—about 20 times. It appears to still be getting replicated, even after I deleted earlier copies.

**Comment by nicosomb** [comment] 2017-12-10 09:27
The issue may come from wallabag.it or from the android app. 
We upgraded wallabag.it few days ago, but maybe the android app has issues (because we updated the android app few weeks ago with upcoming features).

**Comment by nicosomb** [comment] 2017-12-10 09:29
@notabene @ntnsndr could you tell me if this bug appeared when you were offline or online please?

**Comment by di72nn** [comment] 2017-12-10 13:20
I wasn't able to reproduce it, so I only have some generic thoughts:
 * Considering the replication issue, it is almost guaranteed to be a problem with `POST /api/entries`.
  The synchronization of offline changes may be triggered by other actions (like "mark as favorite"), so even if the error is shown after such actions, it still may be caused by sending new URL to the server.
 * On the other hand, the problem may be happening for any type of request, but it is just hard to notice multiple "mark as favorite" actions for the same article.
 * There is no difference between synchronization while online or after being offline. The logic is the same, it just doesn't do anything while offline.
 * Recent app changes are unlikely to cause something like that. But it is still a possibility #644. And it seems to be happening with wallabagger too.

**Comment by ntnsndr** [comment] 2017-12-10 21:34
@nicosomb definitely happening while online, when other networked apps are working fine. 

Thanks for your efforts to fix this. The problem persists.

**Comment by nicosomb** [comment] 2017-12-11 04:40
@ntnsndr could you send me an email with the url and the date it happened please?

**Comment by notabene** [comment] 2017-12-11 08:11
The JSON-in-Android bug appeared when I was online, seems to have disappeared though.

Like @ntnsndr the last article was duplicated a lot of time (40-something so far) on https://app.wallabag.it/unread/list/

**Comment by nicosomb** [comment] 2017-12-11 21:34
I pushed a fix today.

**Comment by Strubbl** [comment] 2017-12-11 22:09
So this issue can be closed?

**Comment by nicosomb** [comment] 2017-12-11 22:33
Not yet. I want to be sure that all is fine. And I pushed a fix but it’s not pushed on the repository

**Comment by biva** [comment] 2018-01-08 18:40
For information, I'm having the same issue on a self-hosted instance of wallabag 2.3.1
Android wallabag app version: 2.0.2
How I got it: 
- Deleted an article
- Made a complete sync

**Comment by schneefux** [comment] 2018-07-27 17:49
I have the same issue and @biva's workaround does not work for me. On every attempt to refresh the app, the last article gets added 2 more times. The server logs do not have any errors. The client throws the error as mentioned above.
However, when I opened the article and pressed the "refresh content" button, the browser refreshes and I can see a warning: `DOMXPath::evaluate(): invalid expression in /[…]wallabag-2.3.2/vendor/j0k3r/graby/src/Extractor/ContentExtractor.php on line 972. Redirecting to /view/1234` and the browser refreshes. I suppose that is the response the client gets as well.
I have 30 articles in the queue. Do you have a workaround for exporting the queued links so I can reset the app?

**Comment by Strubbl** [comment] 2018-07-27 18:39
I do not know a way of exporting the queued links.

**Comment by di72nn** [comment] 2018-07-29 11:46
@schneefux there's no easy way, but it is totally doable.

* If you have root, you can just copy/open the SQLite DB used in the app `/data/data/fr.gaulupeau.apps.InThePoche/databases/wallabag`.
* You can go to "Settings - Miscellaneous - Database location" and select "External storage", after that the DB should be available as `/sdcard/Android/data/fr.gaulupeau.apps.InThePoche.debug/files/wallabag`.

When you get the access to the database file, you will be able to open it with any SQLite browser. For example, something like that may work in a terminal on your phone: `sqlite3 /sdcard/Android/data/fr.gaulupeau.apps.InThePoche.debug/files/wallabag`.

After that you can run this query `select EXTRA from QUEUE_ITEM where ACTION = 1;` to see URLs queued for saving (you can also try `select * from QUEUE_ITEM;` to show all queued entries, in case I made a mistake in the first query).

**Comment by bjoernv** [comment] 2018-09-26 14:58
I have this issue with the Android app connected with my own Wallabag server (version 2.3.3).

**Comment by Moredread** [comment] 2018-12-11 17:11
I have this problem using wallabag.it :/

**Comment by cubicgarden** [comment] 2019-12-15 22:27
I recently bought a new ebook reader (Likebook) installed Wallabag android app and can not sync at all. I also receive the same error as everyone else.
However Wallabag on my existing Android phones (3 of them) work and can sync with no errors at all.

I read something about null values, so removed all the items with less than 1min reading time (that was a real pain btw). But its still the same problem.

I'm also using the wallabag 2.3.0 app on all my Android devices and I'm using Wallabag.it (instead of self hosting). I'm lost at what to do as its seems to only be a problem with fresh devices connecting for me.

**Comment by di72nn** [comment] 2019-12-16 07:55
@cubicgarden 

> I also receive the same error as everyone else.

Please double-check that the error says `JsonEncodingException` and not `JsonDataException`. That makes a huge difference.

Apparently, if the exception is `JsonEncodingException` and `display_errors=off` on the server helps, the error happens because server responds with some non-JSON response (a server error message). I think these should be noticeable in the server logs, ping @nicosomb

**Comment by abe-winter** [comment] 2020-04-26 01:53
Got a `JsonEncodingException` in version 2.3.0 of the android app from f-droid:
![wallabag-moshi](https://user-images.githubusercontent.com/7256523/80295193-d3d69900-873e-11ea-8645-798ba09a5323.png)
I think it's caused by this PDF:
https://openresearch-repository.anu.edu.au/bitstream/1885/98880/2/01_Homer-Dixon_Synchronous_failure%253A_the_2015.pdf
Deleting the PDF from wallabag fixes the error, re-adding it breaks things again.
The error happens when I swipe-down-from-top to reload.
Doesn't cause an error on the web interface, just droid.

**Comment by di72nn** [comment] 2020-04-26 08:26
@abe-winter thanks for the report. It seems to be a problem with the wallabag server. Newer server versions (2.3.8 and 2.4.0 (dev)) can't save the PDF at all.

If you're technically inclined, you can check the `published_by` field on the article - my guess that it's the problem.

**Comment by abe-winter** [comment] 2020-04-26 17:11
@di72nn yes, `published_by` lost some letters:
```sql
sqlite> select published_by from wallabag_entry where url = 'https://openresearch-repository.anu.edu.au/bitstream/1885/98880/2/01_Homer-Dixon_Synchronous_failure%3A_the_2015.pdf';
a:1:{i:0;s:175:"Thomas Homer-Dixon, Brian Walker, Reinette Biggs, Anne-Sophie Cr�pin, Carl Folke, Eric F. Lambin, Garry D. Peterson, Johan Rockstr�m, Marten Scheffer, Will Steffen, Max Troell";}
```
The 'author' field in the PDF has special chars for the names that get mangled: Crépin, Rockström

**Comment by di72nn** [comment] 2020-04-27 08:31
That's actually doesn't look like something that can break syncing with the app.
Can you select all the other fields (except for the content) of this entry?
You can also rewrite this field with a value without special characters to test whether it'll sync.

BTW, if you're using a non-fdroid-build of the app, consider checking out our beta build to help us test compatibility with older wallabag servers (available in [releases](https://github.com/wallabag/android-app/releases) or [opt-in in google play](https://play.google.com/apps/testing/fr.gaulupeau.apps.InThePoche)).

**Comment by abe-winter** [comment] 2020-05-01 16:02
@di72nn I set the field to the result of `serialize(["some string"])` in php and that fixed the json error in the mobile app
```sql
-- I converted the special characters to standard ascii
sqlite> update wallabag_entry set published_by='a:1:{i:0;s:149:"Thomas Homer-Dixon, Brian Walker, Reinette Biggs, Anne-Sophie Crepin, Carl Folke, Eric F. Lambin, Garry D. Peterson, Johan Rockstrom, Marten Scheffer";}' where url = 'https://openresearch-repository.anu.edu.au/bitstream/1885/98880/2/01_Homer-Dixon_Synchronous_failure%3A_the_2015.pdf';
```

**Comment by di72nn** [comment] 2020-05-01 18:05
Yeah, probably caused by SQLite or the way wallabag uses it.

> happy to switch to beta if useful to you

It may be useful, so please do.

**Closed by di72nn** 2020-05-01 18:05 UTC
Labels: Bug, Urgent
