### ISSUE TITLE
app V1.9.x incompatibility with Wallabag V2.0.x

### ISSUE THREAD

**Issue by fodiator** [wallabag/android-app#203] opened 2016-04-07 07:46 UTC
I'm actual not shure if it is known that the current android app seems to be incompatible with the recently released V2.0 server-version?

Seems like a bug to me

Kind regards

**Comment by GLLM** [comment] 2016-04-08 15:03
Same for me !
THe URL to use is not mentioned anymore in the documentation !

**Comment by giovi321** [comment] 2016-04-09 10:14
Same problem here. I get the error "Wallabag service not found; check URL. Error code: 1".

**Comment by gerroon** [comment] 2016-04-12 02:49
I have the same issue

**Comment by tcitworld** [comment] 2016-04-12 08:30
Hi there. It's a work in progress at #204. Expect it at the end of the week.

**Comment by Strubbl** [comment] 2016-04-14 19:59
if you want to follow progress, #210 is the PR to watch for. With those changes basically v2 is supported now.

**Comment by fodiator** [comment] 2016-04-15 15:58
unfortunately V 1.9.9.1 doesn't work for me. Although wallabg server (2.0.1) is operable (and token has been created) the app responds "failed to connect to XXX"
Any idea?

**Comment by Strubbl** [comment] 2016-04-15 16:14
The check fails because the App cannot find the following string on your Wallabag URL:

`<form action="/login_check" method="post" name="loginform">`

Maybe that changed from 2.0.0 to 2.0.1. I don't have that version running. If you can provide the URL to your instance I can double-check it.

**Comment by fodiator** [comment] 2016-04-15 16:20
THX
please test it at https://ip.2hh.at:45443/wallabag

**Comment by Strubbl** [comment] 2016-04-15 16:31
Root cause for this problem is, that the wallabag instance is located in the subdirectory wallabag/, but the app expects it directly in /
That needs to be fixed in several places in the app.

**Comment by fodiator** [comment] 2016-04-15 16:42
OK, thanks
I need to have wallbag in a subdir because i have many different services running on my server
Will close the port now, please advice if you need to have it opened again

**Comment by Strubbl** [comment] 2016-04-15 16:51
No problem, but it would be nice if you can test again if PR #212 is merged.

**Comment by fodiator** [comment] 2016-04-16 10:32
Hi, I've just tested V1.9.9.2 and login (connection test)  is working now, and the right RSS token is catched.
Unfortunately Updating feeds results in a 404 not found message
Kind regards

**Comment by tcitworld** [comment] 2016-04-16 10:35
Did you make sure to save the settings after getting the RSS token ? There's a save button at the bottom of the settings that needs to be pressed so that the new settings must be applied.

**Comment by fodiator** [comment] 2016-04-16 10:42
RSS token settings are saved definately.
Shall I open a port for you again?

**Comment by tcitworld** [comment] 2016-04-16 10:45
If you can do so (I'll create an account).

**Comment by fodiator** [comment] 2016-04-16 10:47
opened

**Comment by tcitworld** [comment] 2016-04-16 10:54
I don't seem to receive the confirmation email to register. I guess your server doesn't allow sending emails. If there's nothing to do about this, can you change your password and provide your credentials at tcit at tcit dot fr ?

**Comment by tcitworld** [comment] 2016-04-16 11:27
Got it. It's an issue with the fact that you're hosted within a subdirectory. The userid in the Feed credentials section is set to `wallabag/userid` instead of `userid`. Just delete the `wallabag/` part in front and it works.

**Comment by fodiator** [comment] 2016-04-16 11:35
Yep, perfect!
It's working now

**Comment by Strubbl** [comment] 2016-04-16 17:33
> The userid in the Feed credentials section is set to wallabag/userid instead of userid

Reads like an open task: only user everything right from the last slash in the string as userid.

**Comment by gerroon** [comment] 2016-04-17 03:16
The latest upgrades are crashing on my device. It seems to connect to the server in the settings but when I sync it crashes.

my server is like (wallabag is at the root) http://server:port

**Comment by Strubbl** [comment] 2016-04-17 09:25
@gerroon so you are only pressing the "test connection" button after entering your server details and the app crashes completely?

**Comment by Nepochal** [comment] 2016-04-17 10:35
@gerroon I had the same problem. Wiping the database in the settings solved it.

**Comment by Strubbl** [comment] 2016-04-17 10:44
Sounds valid. Unfortunately we have no migration path from using a v1 instance and going up to a v2 instance. @Nepochal's hint is the solution here (or you can of course deinstall and install the app again if that is easier for you).

@tcitworld should we wipe the database in the app everytime the URL or the login data changes? Then we should consider adding an issue for that to not forget it.

**Comment by tcitworld** [comment] 2016-04-17 14:20
> @tcitworld should we wipe the database in the app everytime the URL or the login data changes? 

I think we should do this at the same time we move the settings panel to a proper `PreferenceActivity`. We would listen for changes, save them, and eventually wipe database if the url and/or login data changes.

**Comment by sourcenix** [comment] 2016-04-17 20:43
Hi,

I've just setup a new Wallabag instance today. I'm trying to connect with the app, but am unable to get it connected. "Wallabag Service not found". I'm running on a HTTPS secured connection.

I followed the documentation on the front page

1. In a web browser, log in
2. Go to the Config tab
3. Under "Feeds", click "Generate token"
4. On your phone, open Wallabag and go to Settings
5. URL: https://www.framabag.org/u/<username>

I get there and i get that error. Maybe it's the wrong URL?

Which URL am i supposed to use?

**Comment by Strubbl** [comment] 2016-04-17 20:51
@sourcenix Yes, your url is missing the nickname in the end, e.g. for me it would be https://www.framabag.org/u/strubbl

**Comment by sourcenix** [comment] 2016-04-17 20:59
@Strubbl 

Thanks for the reply

I see it removed my formatting.
I had actually written https://www.framabag.org/u/"greaterthan"username"lessthan"

But anyway, this is the URL format i use in the app: https://www.framabag.org/u/sourcenix

And it gives me Wallabag service not found?

**Comment by Strubbl** [comment] 2016-04-17 21:03
@sourcenix Yes, and the app behaves correctly. If i open your link, I get a 404 in my browser, too. Maybe you have a typo in your nickname while registration? Please have a closer look at your activation mail. Don't you get a 404 in the browser when you try to open https://www.framabag.org/u/sourcenix ?

**Comment by GLLM** [comment] 2016-04-17 21:07
SAme issue here with selfhosting :
url is https://sub.domain.tld/wallabag

I get the error "Problèmes relatifs aux autorisations. Code d'erreur : 3"

Help !!
I tried plenty of alterations in the url/username/... nothing

Gllm

**Comment by sourcenix** [comment] 2016-04-17 21:12
I was just using the example crom the documentation
 This is my url HTTPS://wallabag.sourcenix.com/u/sourcenix

I've setup the server as per the instructions. That does give me a 404 though?

**Comment by Strubbl** [comment] 2016-04-17 21:14
@sourcenix Have you tried using just https://wallabag.sourcenix.com/ ?

@GLLM Are you running Wallabag V2?  From source code the error code 3 means "weird, probably authorization problems (maybe cookies expire)". 
If you are selfhosting, the correct url is just https://sub.domain.tld/wallabag

**Comment by sourcenix** [comment] 2016-04-17 21:25
@Strubbl I did try what you suggested. Still the same. The certificate is trusted by the phone so I tried both with and without the checkbox forf SSL, but no difference.

I'll look more at it tomorrow. Thanks.

**Comment by Strubbl** [comment] 2016-04-17 21:26
@sourcenix Please double check the documentation for your webserver if it is apache or nginx: http://doc.wallabag.org/en/v2/user/installation.html#installing-on-apache
If i open https://wallabag.sourcenix.com/ i should see the wallabag login page. If you need more help, please join the chat at gitter. There are more people who can help: https://gitter.im/wallabag/wallabag

**Comment by sourcenix** [comment] 2016-04-17 21:34
OK that's strange. It works fine for me. From mobile phone (4g) an internett proxy and home. The site is definitely up and working. Using the web site as we speak.

**Comment by anarcat** [comment] 2016-04-18 20:47
> Got it. It's an issue with the fact that you're hosted within a subdirectory. The userid in the Feed credentials section is set to wallabag/userid instead of userid. Just delete the wallabag/ part in front and it works.

@tcitworld - this seems to still be a bug in 1.9.9.2 - is this a bug that should be reported seperately?

**Comment by tcitworld** [comment] 2016-04-18 20:48
Nope, patch is not merged yet. https://github.com/wallabag/android-app/pull/215

**Comment by anarcat** [comment] 2016-04-18 20:50
@tcitworld cool thanks for the fast answer, i'll follow #215 then. :)

**Comment by gerroon** [comment] 2016-04-18 23:19
Wpingi the data does not work for me. The app stilll crashes when syncing

**Comment by bigretromike** [comment] 2016-04-20 08:46
I had problem with app but it was because in wallabag url i enter https://mydomain/  the last dash was a error maker ;-)

If someone have problem with 2.0.1 and this app, this could be the problem ;-)

**Comment by sourcenix** [comment] 2016-04-20 09:19
@bigretromike Yes, this was also my problem. I had the trailing slash.

**Comment by GLLM** [comment] 2016-04-20 14:18
I'm indeed running v2 on my server + android app.
And hosting it in a subdir, obviously :)

I'll wait for a fix !

**Comment by ymage** [comment] 2016-04-20 20:39
I had the same crashing app while sync. Starred articles provoke 500 error resulting in crashing android app.

**Comment by tcitworld** [comment] 2016-04-24 16:30
Please check out new update.

**Comment by parquetn** [comment] 2016-04-24 21:33
Hey all,

Just arrived, installed my own server and configured app, however am I the only one getting a 500 error when trying to "mark as read" an article ?

Thanks !

**Comment by benediktg** [comment] 2016-04-25 00:04
@parquetn In my case that error was fixed in wallabag (server) v2.0.2.

**Comment by tcitworld** [comment] 2016-04-25 08:31
@parquetn If you use v2.wallabag.org, it will be updated soon.

**Comment by gerroon** [comment] 2016-04-25 20:50
my crash


I/ActivityManager( 5364): Force stopping fr.gaulupeau.apps.InThePoche appid=10198 user=0: from pid 5364
I/ActivityManager( 5364): Killing 32461:fr.gaulupeau.apps.InThePoche/u0a198 (adj 0): stop fr.gaulupeau.apps.InThePoche
I/WindowState( 5364): WIN DEATH: Window{11ad1dc u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity}
W/ActivityManager( 5364): Force removing ActivityRecord{3895e75f u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity t3454}: app died, no saved state
W/ActivityManager( 5364): Spurious death for ProcessRecord{22cc5e2 0:fr.gaulupeau.apps.InThePoche/u0a198}, curProc for 32461: null
W/PackageManager( 7727): Failure retrieving resources for fr.gaulupeau.apps.InThePoche: Resource ID #0x0
W/PackageManager( 5486): Failure retrieving resources for fr.gaulupeau.apps.InThePoche: Resource ID #0x0
I/log     ( 7727): Launching app://fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity
I/Timeline( 7727): Timeline: Activity_launch_request id:fr.gaulupeau.apps.InThePoche time:63970764
I/ActivityManager( 5364): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity} from uid 10066 on display 0
V/WindowManager( 5364): addAppToken: AppWindowToken{37566b92 token=Token{1ed11d1d ActivityRecord{1aa6c1f4 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity t3455}}} to stack=1 task=3455 at 0
V/WindowManager( 5364): Adding window Window{377d2d5 u0 Starting fr.gaulupeau.apps.InThePoche} at 18 of 23 (after Window{36eead01 u0 fr.neamar.kiss/fr.neamar.kiss.MainActivity})
I/ActivityManager( 5364): Start proc 32679:fr.gaulupeau.apps.InThePoche/u0a198 for activity fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity
V/WindowManager( 5364): Adding window Window{ccdd42 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity} at 18 of 23 (before Window{377d2d5 u0 Starting fr.gaulupeau.apps.InThePoche})
V/WindowManager( 5364): Adding window Window{2cc08a90 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity} at 18 of 24 (before Window{ccdd42 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity})
I/ActivityManager( 5364): Displayed fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity: +732ms
I/Timeline( 5364): Timeline: Activity_windows_visible id: ActivityRecord{1aa6c1f4 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity t3455} time:63971810
V/WindowManager( 5364): Adding window Window{3de026c1 u0 PopupWindow:3d1fa629} at 19 of 23 (after Window{2cc08a90 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity})
I/Timeline(32679): Timeline: Activity_launch_request id:fr.gaulupeau.apps.InThePoche time:63974205
I/ActivityManager( 5364): START u0 {cmp=fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.SettingsActivity} from uid 10198 on display 0
V/WindowManager( 5364): addAppToken: AppWindowToken{215b1af2 token=Token{3c076dfd ActivityRecord{2f324a54 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.SettingsActivity t3455}}} to stack=1 task=3455 at 1
V/WindowManager( 5364): Adding window Window{c61ecf9 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.SettingsActivity} at 20 of 24 (after Window{3de026c1 u0 PopupWindow:3d1fa629 EXITING})
I/ActivityManager( 5364): Displayed fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.SettingsActivity: +384ms
I/Timeline( 5364): Timeline: Activity_windows_visible id: ActivityRecord{2f324a54 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.SettingsActivity t3455} time:63975018
V/WindowManager( 5364): Adding window Window{ef8bed8 u0 PopupWindow:1d3a0ecd} at 20 of 24 (after Window{c61ecf9 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.SettingsActivity})
V/WindowManager( 5364): not Base app: Adding window Window{4a6f084 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.SettingsActivity} at 21 of 25
V/WindowManager( 5364): not Base app: Adding window Window{11e490f0 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity} at 19 of 24
I/Timeline( 5364): Timeline: Activity_windows_visible id: ActivityRecord{1aa6c1f4 u0 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity t3455} time:63980363
E/AndroidRuntime(32679): Process: fr.gaulupeau.apps.InThePoche, PID: 32679
E/AndroidRuntime(32679): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Boolean fr.gaulupeau.apps.Poche.entity.Article.getFavorite()' on a null object referenceE/AndroidRuntime(32679):        at fr.gaulupeau.apps.Poche.network.tasks.UpdateFeedTask.processFeed(UpdateFeedTask.java:347)
E/AndroidRuntime(32679):        at fr.gaulupeau.apps.Poche.network.tasks.UpdateFeedTask.updateByFeed(UpdateFeedTask.java:190)
E/AndroidRuntime(32679):        at fr.gaulupeau.apps.Poche.network.tasks.UpdateFeedTask.updateAllFeeds(UpdateFeedTask.java:124)
E/AndroidRuntime(32679):        at fr.gaulupeau.apps.Poche.network.tasks.UpdateFeedTask.doInBackground(UpdateFeedTask.java:71)
E/AndroidRuntime(32679):        at fr.gaulupeau.apps.Poche.network.tasks.UpdateFeedTask.doInBackground(UpdateFeedTask.java:30)
W/ActivityManager( 5364):   Force finishing activity 1 fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ArticlesListActivity
W/PackageManager( 7727): Failure retrieving resources for fr.gaulupeau.apps.InThePoche: Resource ID #0x0
W/PackageManager( 5486): Failure retrieving resources for fr.gaulupeau.apps.InThePoche: Resource ID #0x0
I/ActivityManager( 5364): Process fr.gaulupeau.apps.InThePoche (pid 32679) has died
W/PackageManager( 7727): Failure retrieving resources for fr.gaulupeau.apps.InThePoche: Resource ID #0x0
I/ActivityManager( 5364): START u0 {act=android.settings.APPLICATION_DETAILS_SETTINGS dat=package:fr.gaulupeau.apps.InThePoche cmp=com.android.settings/.applications.InstalledAppDetails} from uid 10066 on display 0
W/PackageManager( 7727): Failure retrieving resources for fr.gaulupeau.apps.InThePoche: Resource ID #0x0
^@^@^@^@^@^@^@^@^@y

**Comment by Strubbl** [comment] 2016-04-25 21:00
This threads gets confusing. @gerroon I opened a new ticket for your issue: #224

**Comment by khinsen** [comment] 2016-04-29 19:10
I am migrating from my Framabag account (Wallabag 1.9) to a self-hosted 2.0.3 instance. I had the latest Android app, but I uninstalled and reinstalled it because of the database issues mentioned in this thread. I am now at 1.9.9.3, with no obsolete configuration left.

First I entered the URL (no trailing slash) and my credentials, and then pressed "test connection". Result "Echec. Erreur inconnue. Code d'erreur: 4".

I tried to retrieve the RSS feed data nevertheless, which crashed the app.

Any ideas ?

**Comment by khinsen** [comment] 2016-04-29 19:27
Oops.... I got another e-mail with a confirmation code. Apparently the Android app is seen as a different device from the Web browser on the same phone.

That means I am stuck, right? Back to Wallabag 1.9 :-(

**Comment by tcitworld** [comment] 2016-04-29 19:28
Indeed, the android app doesn't yet use the API so you can't use it with 2FA.

**Comment by khinsen** [comment] 2016-05-01 12:26
I disabled 2FA and now the app works fine, so this was the cause of all my problems.

**Comment by mvdkleijn** [comment] 2016-06-10 18:22
Just as an FYI for those reading this...

If you tried to connect with the mobile app and got an "wallabag service not found error code 1" style message due to 2FA or a wrong URL: hosting wallabag (latest version) in a subdirectory works fine for the app **if you delete the data of the app**.

I got that error message due to 2FA and the app kept giving the error even after I disabled 2FA. However, the app worked fine as soon as I deleted the app's data.

Hope this helps anyone.

**Comment by anarcat** [comment] 2016-11-30 02:52
so i found this issue as well and found that 2FA breaks the android app as well. i find this utterly confusing - maybe there should be a warning somewhere in the app for this? i would have totally failed to figure that out if i didn't know about github (and spent a good 20 minutes reading up on issues here :)...

**Comment by di72nn** [comment] 2016-11-30 09:38
@anarcat thanks for pointing this out. Created a separate issue: #359.
// BTW, thanks for commenting in a bunch of other issues.

**Comment by di72nn** [comment] 2016-11-30 09:38
Closed as mostly obsolete.

**Closed by di72nn** 2016-11-30 09:38 UTC
Labels: Bug

**Comment by anarcat** [comment] 2016-11-30 15:00
On 2016-11-30 04:38:32, Dmitriy Bogdanov wrote:
> @anarcat thanks for pointing this out. Created a separate issue: #359.
> // BTW, thanks for commenting in a bunch of other issues.

glad to be of service. :)

a.
