### ISSUE TITLE
Long annotations block synchronization

### ISSUE THREAD

**Issue by panosalevropoulos** [wallabag/android-app#1153] opened 2021-04-18 14:41 UTC
# Issue details
App works as intended except that whenever I sync, an error notification appears with the following information:
```
Unknown error
okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
Stacktrace:
okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:148)
	at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at wallabag.apiwrapper.TokenRefreshingInterceptor.intercept(TokenRefreshingInterceptor.java:65)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall.execute(DefaultCallAdapterFactory.java:104)
	at wallabag.apiwrapper.WallabagService.execAndCheckBody(WallabagService.java:1499)
	at wallabag.apiwrapper.WallabagService.articlesExistByHashes(WallabagService.java:536)
	at wallabag.apiwrapper.BatchExistQueryBuilder.execute(BatchExistQueryBuilder.java:270)
	at fr.gaulupeau.apps.Poche.service.workers.DeletedArticleSweeper.performSweep(DeletedArticleSweeper.java:215)
	at fr.gaulupeau.apps.Poche.service.workers.DeletedArticleSweeper.sweepDeletedArticles(DeletedArticleSweeper.java:79)
	at fr.gaulupeau.apps.Poche.service.workers.DeletedArticleSweeper.sweep(DeletedArticleSweeper.java:56)
	at fr.gaulupeau.apps.Poche.service.tasks.SweepDeletedArticlesTask.run(SweepDeletedArticlesTask.java:17)
	at fr.gaulupeau.apps.Poche.service.tasks.ActionRequestTask.run(ActionRequestTask.java:25)
	at fr.gaulupeau.apps.Poche.service.-$$Lambda$0cveUIqKhxWljSld0gpOhfhYfj0.run(Unknown Source:2)
	at fr.gaulupeau.apps.Poche.service.TaskService.run(TaskService.java:162)
	at fr.gaulupeau.apps.Poche.service.TaskService.lambda$PgumDII_lptJcUDKRD70B1M_ER8(Unknown Source:0)
	at fr.gaulupeau.apps.Poche.service.-$$Lambda$TaskService$PgumDII_lptJcUDKRD70B1M_ER8.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:919)
	Suppressed: okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
		... 32 more
```
### Duplicate?
May be similar to #887, but I think it's different.

### Actual behaviour
Syncing causes error notification to appear. Sync itself appears to be successful. I haven't noticed any affected entries (though tbh I have more than 1000 saved).

### Expected behaviour
Successful sync with no errors.

# Steps to reproduce the issue
1. Sync
2. Error notification appears

# Environment details
- **wallabag app version**: 2.4.2
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): F-Droid
- **Android OS version**: 10
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): LineageOS
- **Android hardware**: Xiaomi Mi 9 Lite
- **wallabag server version**: I'm on wallabag.it
- **Do you have Two-Factor-Authentication enabled?**: no

# Your experience with wallabag Android app
The app is great, very lightweight and just works. This error doesn't affect the app's functionalities.

**Comment by di72nn** [comment] 2021-04-18 15:11
Duplicate of #909.

Something is wrong with a big HTTP GET request over HTTP2.

You can uncheck `Enable "Deleted article sweep" after "Fast" sync` to avoid receiving that error.

**Comment by di72nn** [comment] 2021-04-18 15:13
> I'm on wallabag.it

That's troubling.

**Comment by panosalevropoulos** [comment] 2021-04-18 17:33
> You can uncheck Enable "Deleted article sweep" after "Fast" sync to avoid receiving that error.
Thanks, that did it.

> That's troubling.
What's troubling about using wallabag.it?

**Comment by di72nn** [comment] 2021-04-18 19:04
> What's troubling about using wallabag.it? Edit: I guess it's because I can't help with fixing the issue. Sorry :)

Nah, I meant that many people may encounter the problem in case of wallabag.it (the other report was a self-hosted instance). I guess I'll have to try to reproduce it now.

**Comment by panosalevropoulos** [comment] 2021-04-18 23:50
I now get a persistent error, which seems to affect syncing completely. I don't know if it's related to the unchecked setting, but I didn't have have this problem before. This is the error:

```
Server error
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 
Stacktrace:
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 
	at wallabag.apiwrapper.WallabagService.checkResponse(WallabagService.java:1525)
	at wallabag.apiwrapper.WallabagService.checkResponseBody(WallabagService.java:1503)
	at wallabag.apiwrapper.WallabagService.execAndCheckBody(WallabagService.java:1499)
	at wallabag.apiwrapper.WallabagService.lambda$addAnnotation$15$WallabagService(WallabagService.java:1287)
	at wallabag.apiwrapper.-$$Lambda$WallabagService$Hyj54SgcQsjCPFdH_O_WQtzPai4.run(Unknown Source:10)
	at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:140)
	at wallabag.apiwrapper.WallabagService.addAnnotation(WallabagService.java:1287)
	at wallabag.apiwrapper.WallabagService.addAnnotation(WallabagService.java:1263)
	at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.syncAddAnnotationToArticle(OfflineChangesSynchronizer.java:417)
	at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.syncOfflineQueue(OfflineChangesSynchronizer.java:126)
	at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.synchronize(OfflineChangesSynchronizer.java:68)
	at fr.gaulupeau.apps.Poche.service.tasks.SyncOfflineChangesTask.run(SyncOfflineChangesTask.java:17)
	at fr.gaulupeau.apps.Poche.service.tasks.ActionRequestTask.run(ActionRequestTask.java:25)
	at fr.gaulupeau.apps.Poche.service.-$$Lambda$0cveUIqKhxWljSld0gpOhfhYfj0.run(Unknown Source:2)
	at fr.gaulupeau.apps.Poche.service.TaskService.run(TaskService.java:162)
	at fr.gaulupeau.apps.Poche.service.TaskService.lambda$PgumDII_lptJcUDKRD70B1M_ER8(Unknown Source:0)
	at fr.gaulupeau.apps.Poche.service.-$$Lambda$TaskService$PgumDII_lptJcUDKRD70B1M_ER8.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:919)
```

**Comment by di72nn** [comment] 2021-04-19 11:04
The server fails to process the request when the app tries to sync (client->server) an annotation that you added.
Go to `Settings -> Miscellaneous -> Local changes` and press "Dump to file", it will export local changes that are not synchronized. The first item should be related to the problematic annotation. You can at least find the ID of the problematic article if you're interested.
On the same screen you can press "Remove first local queue item" to drop the change (the app won't try to sync it to the server). We didn't have issues with annotation sync, so we don't have any means to recover the data - you'll have to manually add the annotation through the web UI.

**Comment by di72nn** [comment] 2021-04-19 11:06
@nicosomb any idea why the server crashes (HTTP 500) when an annotation is added?

I just tried adding an annotation without a problem, so it probably has something to do with the data.

**Comment by panosalevropoulos** [comment] 2021-06-04 16:07
I found out how to replicate this error. Wallabag.it (I don't know about other instances) allows annotations only up to 1000 characters. In the mobile app, if you add an annotation that exceeds this limit, it simply cannot sync. This should be an easy fix (just put the same character limit in the app), although I don't see why there is a character limit in the first place.

**Comment by di72nn** [comment] 2021-06-16 16:59
Thanks for finding the cause!

Long annotations indeed cause errors.
Self-hosted 2.4.2 answers with HTTP 400, "Validation Failed": "The quote is too long. It should have 10000 characters or less." and is capable of handling of quotes of at least 7k characters.
wallabag.it, on the other hand, seems to answer with HTTP 500 as soon as the quote length reaches 1001 characters.
Maybe the PostgreSQL schema has lower limit?

The quote in the annotation is not actually used, so truncating it on the client should be an acceptable fix.

**Closed** 2021-06-16 21:01 UTC
Labels: Bug

**Comment by di72nn** [comment] 2021-06-17 09:24
The app now truncates annotation quotes at 10k, but wallabag.it still has an issue with 1k+ (which should be dealt with not in this repo).
