### ISSUE TITLE
being able to act on post from the full list (context menu for lists)

### ISSUE THREAD

**Issue by foxmask** [wallabag/android-app#233] opened 2016-05-01 13:57 UTC
It wiil be useful if we could have a list of possible actions from the list of post, by pressing a long moment on a  post , to delete it or reaffect to a tag

**Comment by Strubbl** [comment] 2016-05-03 17:36
This issue sounds like your issue #227. I close this as duplicate. If i was wrong, please clarify before reopening.

**Comment by foxmask** [comment] 2016-05-03 18:35
Hello, in fact its not the same , on #227 i'd like to be able to select several post to drop them in once for exemple. Here i'd like to be able to open a list of actions by a long press on one article and then set a tag, or delete it or archive it or set a star and so on. 
But if you think #227 will also handle this feature, that is nice

**Comment by Strubbl** [comment] 2016-05-03 18:40
Okay, now i understand. Thanks for clarifying

**Comment by di72nn** [comment] 2016-05-03 18:56
I believe the issue is the same as #139.

**Comment by foxmask** [comment] 2016-05-03 19:01
True vut for v2 as #139 is for 1.9

**Comment by biva** [comment] 2017-11-07 08:02
Hello, any progress on this issue? I'd love to see this context menu happening. Available for testing if needed.

**Comment by Strubbl** [comment] 2017-11-07 15:40
AFAIK nobody is working on this issue currently. 
@biva are you also available for adding some code to implement this?

**Comment by Strubbl** [comment] 2018-01-08 18:16
#676 also requests (un)fav, (un)archive as actions of the long press menu

**Comment by BNolet** [comment] 2019-03-10 16:02
3 years later...?

**Comment by foxmask** [comment] 2019-10-27 14:33
For le it's dead so ...

**Comment by di72nn** [comment] 2019-10-28 11:41
@foxmask
Closing an issue for no reason is not constructive. Just because nobody could put enough effort to do it doesn't mean nobody cares. Same goes for the other issues you closed recently.

**Comment by foxmask** [comment] 2019-10-28 11:51
2 years w/o any activity for me means it's over. 
You can keep it open .

**Closed** 2020-05-08 11:39 UTC
Labels: Feature, UI
