### ISSUE TITLE
Can't add Link from Android App

### ISSUE THREAD

**Issue by ppmt** [wallabag/android-app#37] opened 2014-09-08 19:40 UTC
I am having a strange problem which is most likely related to the server setting but can't work it out

I was on chat with tcit who advised me to open an issue. I must say that when I used his dev wallabag all was fine (hence the suspected server)

When I installed everything was compatible and green

Symptoms are: 
1/ From Linux with Firefox and Firefox extensions I can add URL to Wallabag no problem
2/ From my tablet using a 4.4.4 and the Wallabag app I can't add URL Wallabag

When I share the the url using "Bag it" I am redirected to the  Wallabag login as expected. After entering the credential the page refresh back to the login page and at the top it is now written
"welcome to your wallabag" and that's it.

Here is a debug from when it doesn't work from the tablet  
2014/09/08_10:33:51 - 31.51.86.65 - storage type sqlite
2014/09/08_10:33:51 - 31.51.86.65 - login successful
2014/09/08_10:33:51 - 31.51.86.65 - redirect to http://www.xxxx.org/wallabag/?action=add&url=aHR0cDovL3d3dy53ZWVrZW5kYmFrZXJ5LmNvbS93ZWJzaG9wL25sLw%3D%3D%0A
2014/09/08_10:33:52 - 31.51.86.65 - storage type sqlite
2014/09/08_10:39:47 - 31.51.86.65 - storage type sqlite
2014/09/08_10:39:51 - 31.51.86.65 - storage type sqlite

and one when it works from Firefox in Linux

2014/09/08_11:03:02 - 31.51.86.65 - login successful
2014/09/08_11:03:02 - 31.51.86.65 - redirect to http://www.xxxx.org/wallabag/?action=add&url=aHR0cDovL2dldGJvb3RzdHJhcC5jb20vZ2V0dGluZy1zdGFydGVkLw==
2014/09/08_11:03:03 - 31.51.86.65 - storage type sqlite
2014/09/08_11:03:05 - 31.51.86.65 - add link http://getbootstrap.com/getting-started/
2014/09/08_11:03:05 - 31.51.86.65 - redirect to ?view=home&closewin=true
2014/09/08_11:03:05 - 31.51.86.65 - storage type sqlite

I must say that Wallabag is installed and hosted site so it is possible that something is wrong

I can provide the link to a phpinfo if required by email and of course I can provide any other info that might be required

**Comment by chrisdadswell** [comment] 2015-01-21 22:32
Same problem here. Self hosted. Works in Chrome on desktop but not on Android chrome.

**Comment by tcitworld** [comment] 2015-01-21 22:49
Seems that android (Chrome, I guess) encodes the ending `==` as `%3D%3D%0A` but it always works however. Moreover, I always manage to save with my own android app for the URLs @ppmt provided. And the URL accessed is exactly the same.

I'll need more info to keep looking for this bug, in order to try with emulators : 
* Device name/constructor/ROM/Android Version
* Browser opened when asked to login

**Comment by chrisdadswell** [comment] 2015-01-22 08:00
Hi tcitworld,

I did some extra testing last night and can confirm this is only an issue on Android when running Chrome Beta.

I installed standard Chrome and can login as expected to bag URLs.

Thanks!
Christian.

**Comment by tcitworld** [comment] 2015-01-22 15:44
I'll try to test with Chrome Beta then.

**Comment by tcitworld** [comment] 2015-11-12 20:13
This needs to be reproduced with the new [beta](https://play.google.com/apps/testing/fr.gaulupeau.apps.InThePoche) builds (Google Play only for now). I didn't manage to reproduce it.

**Comment by djibux** [comment] 2016-01-07 09:32
I'm having the issue with version 1.9.3.1 with a self hosted 1.9.1 bag.  Adding articles is impossible.  Here is a Logcat:

```
java.io.FileInputStream.close() from FileInputStream.java:114 waiters=0 for 193ms
W/System.err(12230): java.net.SocketTimeoutException
W/System.err(12230): 	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
W/System.err(12230): 	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
W/System.err(12230): 	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
W/System.err(12230): 	at okio.Okio$2.read(Okio.java:139)
W/System.err(12230): 	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
W/System.err(12230): 	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
W/System.err(12230): 	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
W/System.err(12230): 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
W/System.err(12230): 	at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
W/System.err(12230): 	at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
W/System.err(12230): 	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:906)
W/System.err(12230): 	at com.squareup.okhttp.internal.http.HttpEngine.access$300(HttpEngine.java:92)
W/System.err(12230): 	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:891)
W/System.err(12230): 	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:749)
W/System.err(12230): 	at com.squareup.okhttp.Call.getResponse(Call.java:268)
W/System.err(12230): 	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
W/System.err(12230): 	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
W/System.err(12230): 	at com.squareup.okhttp.Call.execute(Call.java:79)
W/System.err(12230): 	at fr.gaulupeau.apps.Poche.network.WallabagService.exec(WallabagService.java:248)
W/System.err(12230): 	at fr.gaulupeau.apps.Poche.network.WallabagService.executeRequestForResult(WallabagService.java:222)
W/System.err(12230): 	at fr.gaulupeau.apps.Poche.network.WallabagService.executeRequest(WallabagService.java:211)
W/System.err(12230): 	at fr.gaulupeau.apps.Poche.network.WallabagService.executeRequest(WallabagService.java:207)
W/System.err(12230): 	at fr.gaulupeau.apps.Poche.network.WallabagService.addLink(WallabagService.java:88)
W/System.err(12230): 	at fr.gaulupeau.apps.Poche.network.tasks.AddLinkTask.doInBackground(AddLinkTask.java:69)
W/System.err(12230): 	at fr.gaulupeau.apps.Poche.network.tasks.AddLinkTask.doInBackground(AddLinkTask.java:22)
W/System.err(12230): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
W/System.err(12230): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err(12230): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err(12230): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err(12230): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err(12230): 	at java.lang.Thread.run(Thread.java:818)
W/ResourceType( 1419): No package identifier when getting value for resource number 0x00000000
W/PackageManager( 1419): Failure retrieving resources for fr.gaulupeau.apps.InThePoche: Resource ID #0x0
W/IInputConnectionWrapper(12230): showStatusIcon on inactive InputConnection
W/ResourceType( 1419): No package identifier when getting value for resource number 0x00000000
W/PackageManager( 1419): Failure retrieving resources for fr.gaulupeau.apps.InThePoche: Resource ID #0x0
```

I had data enabled and managed to get the articles from the server.

**Comment by tcitworld** [comment] 2016-01-07 12:28
Seems like a timeout exception we don't handle. The original error should be fixed.
Maybe your server doesn't reply fast enough ?

**Comment by djibux** [comment] 2016-01-07 12:50
I'll try this out in a different setup (for instance using wifi) and let you know.  Downloading articles from the server is almost instantaneous but maybe my upload is bad.

**Comment by djibux** [comment] 2016-01-10 11:01
OK indeed it seems to be a network timeout error.  I keep having it randomly but it works most of the time.  Sorry for the trouble.

**Comment by tcitworld** [comment] 2016-01-10 11:02
Thanks for reporting, though, we'll handle the exception.

**Comment by djibux** [comment] 2016-01-24 13:36
I'm having another issue but it might be linked to that one.  Please let me know if I should file a new issue.

* I have added a few links offline.
* When trying to sync those with the server, once online, the process hangs and fails with the error “timeout”.
* A new element called “untitled” appears in my list of articles (so if I try and sync offline links to the server multiple times, I get multiple “untitled” entries).  That probable shouldn't be the case.

Also, rather than stopping the whole process on a timeout, I feel the process should move to the next link.  I currently have 6 offline links, and since the first one won't sync, there seems to me I have no way to push the 5 others to the server…

Thanks for your help.

**Comment by di72nn** [comment] 2016-09-24 12:37
The old problems are not reproduced, the later discussed problem is partially fixed (url upload), partially replaced (connection timeout) with #307.

**Closed by di72nn** 2016-09-24 12:37 UTC
Labels: Bug, Needs to be reproduced
