### ISSUE TITLE
Can't connect to my wallabag instance

### ISSUE THREAD

**Issue by pierrec18** [wallabag/android-app#694] opened 2018-01-29 18:51 UTC
Hi,

I installed Wallabag in a docker instance on my synology and everything works fine on web browser like Chrome or Firefox locally.
To access to my Wallabag instance from the outside, I setted an reverse proxy with Synology, HTTPS and let's encrypt certificat. Again, everything works fine with web browser. Anyway when i tried to configure the Wallabag android app with my instance i get the error "Wallabag service not found". I tried to configure the app with the local IP, it worked.
It seems that the problem is around the reverse proxy, the android app and the HTTPS but I cannot find a good solution.

if the problem is not related to the application, I apologize and will remove this issue.

Thank you by advance,

Pierre

**Comment by Strubbl** [comment] 2018-01-29 19:00
I assume you are running wallabag v2.x. Or which version are you running?

The error message you are posting is seen when the app cannot detect the login page: https://github.com/wallabag/android-app/blob/f01a162b9304cc8a16f270e64c2537259f2b6c06/app/src/main/java/fr/gaulupeau/apps/Poche/network/WallabagWebService.java#L108

This usually comes from minifying the HTML source by the web server before delivering it to the client. This issue is known and reported in #497. Please see also the refererred comment in that issue.
Please deactive minifying the sources. 
If that is also your issue too, you can close this one. 

If not, please check that your login page matches the regex for the login form https://github.com/wallabag/android-app/blob/f01a162b9304cc8a16f270e64c2537259f2b6c06/app/src/main/java/fr/gaulupeau/apps/Poche/network/WallabagWebService.java#L29 and the regex for the logo https://github.com/wallabag/android-app/blob/f01a162b9304cc8a16f270e64c2537259f2b6c06/app/src/main/java/fr/gaulupeau/apps/Poche/network/WallabagWebService.java#L32

**Comment by pierrec18** [comment] 2018-01-29 19:39
Thank for your quick answer but I didn't activate the minifying from the server. 
So I do not think it comes from there.
I checked the regex and everything it's OK.
However, everything is OK when I do it in my local network without reverse proxy. The problem is through reverse proxy.

**Comment by di72nn** [comment] 2018-01-29 19:43
You should also check for HTTPS -> HTTP redirects (maybe the app makes an HTTP request and receives some stub page). Somehow it is a common issue.

**Comment by Strubbl** [comment] 2018-01-29 19:49
Please also check var/logs/prod.log of your wallabag server instance. Maybe that gives some insight

**Comment by pierrec18** [comment] 2018-01-29 20:26
I looked into var/logs/prod.log, I didn't see anything in particular.
I modified my reverse proxy to do it without https and actually, it works better but i'm not very confident to use http instead of https.
Is there a solution ?

**Comment by Strubbl** [comment] 2018-01-29 20:35
Okay, so the problem is not with the app. Therefore i am closing this issue.

The solution might be to fix your reverse proxy for https. Maybe someone in the Gitter chat can help: https://gitter.im/wallabag/wallabag
There are some people using Synology+wallabag. Maybe if you can share you config in the chat, somebody is able to help you find your problem in the reverse proxy configuration.

**Closed by Strubbl** 2018-01-29 20:35 UTC
