### ISSUE TITLE
Cannot log into wallabag.it when 2 factor is enabled

### ISSUE THREAD

**Issue by betsythefc** [wallabag/android-app#685] opened 2018-01-11 18:14 UTC
Wallabag.it supports 2FA over email. When logging in with the app, I get the error "Unknown page after signin". In order to log in I can't have 2fa enabled.

**Comment by Strubbl** [comment] 2018-01-11 18:33
Yes, this is a known issue: #359
Closing this one as duplicate of #359

**Comment by betsythefc** [comment] 2018-01-11 18:34
@Strubbl, whoops, I searched and didn't find a duplicate, thanks for linking.

**Closed by Strubbl** 2018-01-11 18:33 UTC

**Comment by Strubbl** [comment] 2018-01-11 18:34
no problem :)
