### ISSUE TITLE
Titles appearing on multiple lines

### ISSUE THREAD

**Issue by BNolet** [wallabag/android-app#772] opened 2019-03-10 02:30 UTC
# Issue details
Titles that appear normally on the server appear in multiple lines on the android app. Does not happen with all articles.

### Duplicate?
Have you searched the issues of this repository if your issue is already known? yes

### Actual behaviour
Certain titles appear on multiple lines, word-by-word

### Expected behaviour
Titles should appear on single line until overflow

# Environment details
- **wallabag app version**: 2.2.0
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): FDroid
- **Android OS version**: 8.0
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): Stock
- **Android hardware**: Moto Z^2 Play
- **wallabag server version**: 2.3.5
- **Do you have Two-Factor-Authentication enabled?**: no

# Your experience with wallabag Android app
Have you had any luck using wallabag Android app before? (Sometimes we get tired of reading bug reports all day and a lil' positive end note does wonders)

I love the app and I'm really happy that the black theme was finally fixed! :)

**Comment by Strubbl** [comment] 2019-03-10 08:57
hi @BNolet , thanks for your report. 
What do you exactly mean by certain titles appearing on multiple lines?
Is this because the article's titles are so long? 

I haven't experience this error yet. What do i need to do to try to reproduce this error?
Is it possible to post a screenshot of this error?

**Comment by BNolet** [comment] 2019-03-10 13:47
My apologies for the hasty bug report.


https://www.tecmint.com/systemd-replaces-init-in-linux/

This link is one of the ones who's title appeared on multiple lines. 

Something
Like
This
Was
Happening

I'll provide a screenshot in not too long. This link was saved through the wallabagger extension though most articles saved via that method did not result in erroneous multi-line titles.

**Comment by Strubbl** [comment] 2019-03-10 14:03
No problem. Thanks for your report and your support in clarifying the issue. 

Now i think, i got the idea of the bug. I tested your article, but unfortunately the article list looks ok in my app. We are talking about the view of the article list, don't we?

This error did not occur in previous versions, e.g. 2.1.0, of the app? Or have you seen it before app version 2.2.0?

**Comment by BNolet** [comment] 2019-03-10 14:09
Here's a screenshot from 2.1.0:
![image](https://user-images.githubusercontent.com/10198484/54086113-64280380-431c-11e9-85af-d5f67defa26b.png)
The link for this article is the following: https://krebsonsecurity.com/2019/02/bomb-threat-hoaxer-exposed-by-hacked-gaming-site/


Here's a screenshot from 2.2.0:
![image](https://user-images.githubusercontent.com/10198484/54086119-6db16b80-431c-11e9-929e-fae910d92aa6.png)

Yes, this is in the list of articles.

**Comment by Kdecherf** [comment] 2019-03-10 14:44
Hello there,

Could you update the server version and refetch these articles to see if it's still there? I suspect it's an issue with one the wallabag's dependencies recently fixed.

**Comment by BNolet** [comment] 2019-03-10 15:08
Interesting enough it seems it wasn't an issue with the Android app but indeed with the server. Here's a screenshot of how I figured that part out:
![multilinetitlewallabag](https://user-images.githubusercontent.com/10198484/54086911-55454f00-4324-11e9-920a-c439afba5e37.png)

The issue was with the fetching process rather than the issue being during viewing as the wrongly displayed title persisted after update. 

After updating the server to 2.3.7 and re-fetching the "offending" articles, the issue does not persist.

Thanks for the help all. If this issue re-appears, I'll try these steps again and file the issue in the server repo.

**Comment by Kdecherf** [comment] 2019-03-10 15:23
Great :+1:

I'm closing this issue then.

**Closed by Kdecherf** 2019-03-10 15:23 UTC
