### ISSUE TITLE
View image full screen / zoom

### ISSUE THREAD

**Issue by jtagcat** [wallabag/android-app#1203] opened 2021-09-30 17:00 UTC
# Issue details

Quite often, there are images of graphs, yet they are way too small to read.

### Actual behaviour
- Tapping or holding on the image does nothing.

### Expected behaviour
- Tapping opens the image externally, or allows more advanced full screen zooming capabilities.

# Environment details
- **wallabag app version**: v2.4.3 (229
- **wallabag app installation source**: F-Droid
- **Android OS version**: 11
- **Android ROM** LineageOS
- **Android hardware**: dumpling

Images have been downloaded, offline.

**Comment by Strubbl** [comment] 2021-11-01 18:39
duplicate of #616

**Closed by Strubbl** 2021-11-01 18:39 UTC
