### ISSUE TITLE
FR: Select and remove multiple articles at once

### ISSUE THREAD

**Issue by mwoz123** [wallabag/android-app#967] opened 2020-05-04 19:30 UTC
# Issue details
Deleting one article after one in wallabag android is very annoying when you don't do that after each article (when using extenal reader app). 

E.g. to delete 3 articles you have to 
1. in article list open an article 
2. click on menu
3. click on delete
4. confirm deletion 
5. (again) in article list open an article 
6. click on menu
7. click on delete
8. confirm deletion 
9. (again) in article list open an article 
10. click on menu
11. click on delete
12. confirm deletion 

Please imagine deleting 10 articles or more...

### Duplicate?
Have you searched the issues of this repository if your issue is already known? NO

### Actual behaviour
Deleting articles in wallabag application is very roboust.

### Expected behaviour
Deleting in application should be easier. Eg. ability to select many articles at once and press "delete selected" button

# Steps to reproduce the issue
1. Open article list
2. try to delete 10 articles

# Environment details
- **wallabag app version**: current google play
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual):  gplay
- **Android OS version**: 9
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…):  stock
- **Android hardware**: 
- **wallabag server version**: 
- **Do you have Two-Factor-Authentication enabled?**: yes/no

# Your experience with wallabag Android app
Good. Thanks for solid and free app:)

**Comment by di72nn** [comment] 2020-05-05 08:43
Unlikely to be fixed unless someone steps in to help with UI. Most of the UI needs to be redone anyway.

I added a context menu for non-bulk actions in #931.

Duplicate of #227.

**Closed by di72nn** 2020-05-05 08:43 UTC
