### ISSUE TITLE
Improve SSL/TLS configuration

### ISSUE THREAD

**Issue by TakerMc** [wallabag/android-app#613] opened 2017-07-13 17:31 UTC
Hello,

I've tried to configure the wallabag app on my phone, but every time i get this error: 

![screen](https://lut.im/U0TQKotbaC/4YBdjdeeMbxX9J9F.jpg)

My wallabag is self-hosted. Here's my virtual host (the SSL part): 

`ssl_certificate `/etc/letsencrypt/live/wallabag.taker.fr/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/wallabag.taker.fr/privkey.pem;
ssl_protocols TLSv1.2;
ssl_ecdh_curve prime256v1;
ssl_ciphers EECDH+AESGCM:EECDH+AES;
ssl_prefer_server_ciphers on;`

Anyone else is having the same issue ?

**Comment by di72nn** [comment] 2017-07-13 17:55
Hi.

What's your Android version (also, is it stock or third-party version)?

Try toggling "Custom SSL settings" (in Advanced connection settings). The "Connection Wizard" uses the default value, so you'll have to test connection from settings (by pressing "Autofill" in the Connection settings after you filled in URL, username and password).

Also, can you open your wallabag URL in the stock browser on your phone?

**Comment by Strubbl** [comment] 2017-07-13 17:55
ssl looks good: https://www.ssllabs.com/ssltest/analyze.html?d=wallabag.taker.fr

yeah, android version would be interesting

**Comment by TakerMc** [comment] 2017-07-13 18:54
My phone is on Android 7.0 (cf screen below)

![screen](https://lut.im/PaI4fMkQnf/mzh14lN70Im9UICA.jpg)

I've tried toggling Custom SSL settings, still have this error. I can access my wallabag using my browser.

**Comment by Strubbl** [comment] 2017-07-13 19:26
Maybe it's a problem with your Android version: https://issuetracker.google.com/issues/37122132

@di72nn in a different app, this was fixed with this commit: https://github.com/Vavassor/Tusky/commit/8994d81c66c6cc73925ab60905150730d939e804
is this valid for our app?

**Comment by di72nn** [comment] 2017-07-13 19:41
I tried to connect with my old Android 4.4 device and it seems to work fine (there was auth error of course, but the handshake was fine).

So yeah, it seems to be related to the regression in Android 7.

That fix in Tusky may work, but it is too complex for me to examine at the moment. [Link](https://github.com/Vavassor/Tusky/blob/master/app/src/main/java/com/keylesspalace/tusky/util/OkHttpUtils.java).

@TakerMc upgrading Android is the best solution. If you can't do it, you can probably try different server configurations (add some non-elliptic-curve crypto probably). Of course you can wait for us to try to work around it, but it may take some time.

**Comment by TakerMc** [comment] 2017-07-13 21:00
For now i can't update my phone, so I dit what you have recommended me. I've add non-elliptic-curve ciphers and it works. Thanks @di72nn and @Strubbl  ! :+1:

**Comment by di72nn** [comment] 2020-02-16 08:44
Move to Conscrypt should improve the situation: #823.

**Closed by di72nn** 2020-02-16 08:44 UTC
Labels: Improvement
